version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '3333:3333'

volumes:
  psql-data:
